### ISSUE TITLE
tbl_df() not exported anymore by tibble

### ISSUE THREAD

**Issue by krlmlr** [karthik/randNames#3]
https://github.com/hadley/tibble/pull/57

This gives me revdep check errors. We could export this again (with a warning), but I'd prefer if randNames just used as_data_frame() or (for tibble >= 1.1) as_tibble().

Do you think you can submit an update to CRAN in the next few weeks?

CC @hadley.

**Comment by karthik** [comment]
@krlmlr I've just pushed a fix to the package.  I can push an update soon if this looks ok to you.

**Comment by krlmlr** [comment]
Awesome, thanks for the quick fix! I'll try to submit tibble to CRAN then, please submit at your leisure to fix the breakage that the tibble update causes.

**Comment by krlmlr** [comment]
Oh, it's on CRAN _already_. Wow. Thanks again.
