### ISSUE TITLE
[bug] Doesn't work under a proxy.

### ISSUE THREAD

**Issue by ELToulemonde** [karthik/randNames#4]
Hi,

I'm trying to use your package under a proxy.
```R
dat_nam <- rand_names(100, gender = "male", nationality = "FR")
```
Is thorwing the following eror:
```R
Error: lexical error: invalid char in json text.
                                       <HTML><HEAD>  <TITLE>Access Den
                     (right here) ------^
```

This is because you are immediatly extracting content from result without checking if it raised an error.

For example using `httr::stop_for_status`.

I will create a pull request to fix this bug.

**Comment by karthik** [comment]
A PR would be welcome!

**Comment by ELToulemonde** [comment]
Hi, I did it and you accepted it a few days ago... ;)

I close the issue.
